pipeline {
    agent {
        label 'AGENT-1'
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select Action')
    }
    stages {
        stage('Init and Plan') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-cred') {
                    sh """
                        cd 70-cdn
                        terraform init -reconfigure
                        terraform plan -out=tfplan
                    """
                }
            }
        }
        stage('Apply or Destroy') {
            // input {
            //     message "Should we continue to ${params.ACTION}?"
            //     ok "Yes, we should."
            // }
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-cred') {
                    sh """
                        cd 70-cdn
                        if [ ${params.ACTION} == 'apply' ]
                        then
                            terraform apply -auto-approve tfplan
                        elif [ ${params.ACTION} = 'destroy' ]
                        then
                            terraform destroy -auto-approve
                        fi
                    """
                }
            }
        }
        stage('Parallel-1') {
            when {
                expression {params.ACTION == 'destroy'}
            }
            parallel {
                stage('ALB') {
                    steps {
                        build job: '60-alb', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
                    }
                }
                stage('ECR') {
                    steps {
                        build job: '50-ecr', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
                    }
                }
                stage('ACM') {
                    steps {
                        build job: '40-acm', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
                    }
                }
                stage('EKS') {
                    steps {
                        build job: '30-eks', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
                    }
                }
                stage('Bastion') {
                    steps {
                        build job: '20-bastion', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
                    }
                }
            }
        }
        stage('Parallel-2') {
            when {
                expression {params.ACTION == 'destroy'}
            }
            parallel {
                stage('destroy SG') {
                    steps {
                        build job: '10-sg', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
                    }
                }
            }
        }
    }

    post {
        always{
            echo "This sections runs always"
            deleteDir()
        }
        success{
            echo "This section run when pipeline success"
        }
        failure{
            echo "This section run when pipeline failure"
        }
    }
}